### ISSUE TITLE
dbt Cloud Job Status API response throws Cannot deserialize value of type java.time.Duration from String "10.0"

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-dbt#159]
### Describe the issue

Since Wed, Nov 6, 2024 9:04 AM, when checking status of DBT Cloud job it throws the error:
Error is `Cannot deserialize value of type `java.time.Duration` from String "10.0"`

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/51c11f93-d50b-49e0-ad6c-9b7a2fc0a8e0">

### Environment

- Kestra Version: 0.19.8

**Comment by anna-geller** [comment]
@mgabelle the fix was already pushed, can the issue be closed?

**Comment by aballiet** [comment]
> @mgabelle the fix was already pushed, can the issue be closed?

Yes!
