### ISSUE TITLE
dbt Cloud Support for different tenants / hosts

### ISSUE THREAD

**Issue by christophs91** [kestra-io/plugin-dbt#92]
### Feature description

Hi,

I was trying to test the dbt-cloud plugin in kestra but as our dbt Cloud Tenant is hosted in Europe the API Call is not working.

In the AbstractDbtCloud.java is a hardcoded version of the tenant for the US region.

`DefaultHttpClient client = (DefaultHttpClient) FACTORY.createClient(URI.create("https://cloud.getdbt.com").toURL(), httpConfig);`

There are overall three different tenants (https://docs.getdbt.com/dbt-cloud/api-v2#/)

Production (US): https://cloud.getdbt.com
Production (Europe): https://emea.dbt.com
Production (AU): https://au.dbt.com

It is also possible to host dbt Cloud on a Private Hosts (https://docs.getdbt.com/docs/cloud/about-cloud/access-regions-ip-addresses).

Might there be a chance to have an additional parameter to set the tenant / host url?

Thanks and best regards,
Christoph

**Comment by anna-geller** [comment]
you're totally right, we'll see how soon we can fix that
